config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                   Prefix Verb   URI Pattern                         Controller#Action
#         new_user_session GET    /users/sign_in(.:format)            devise/sessions#new
#             user_session POST   /users/sign_in(.:format)            devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)           devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)       devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)      devise/passwords#edit
#            user_password PATCH  /users/password(.:format)           devise/passwords#update
#                          PUT    /users/password(.:format)           devise/passwords#update
#                          POST   /users/password(.:format)           devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)             devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)            devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)               devise/registrations#edit
#        user_registration PATCH  /users(.:format)                    devise/registrations#update
#                          PUT    /users(.:format)                    devise/registrations#update
#                          DELETE /users(.:format)                    devise/registrations#destroy
#                          POST   /users(.:format)                    devise/registrations#create
#                    sites GET    (/:locale)/sites(.:format)          sites#index {:locale=>/en|ru/}
#                          POST   (/:locale)/sites(.:format)          sites#create {:locale=>/en|ru/}
#                 new_site GET    (/:locale)/sites/new(.:format)      sites#new {:locale=>/en|ru/}
#                edit_site GET    (/:locale)/sites/:id/edit(.:format) sites#edit {:locale=>/en|ru/}
#                     site GET    (/:locale)/sites/:id(.:format)      sites#show {:locale=>/en|ru/}
#                          PATCH  (/:locale)/sites/:id(.:format)      sites#update {:locale=>/en|ru/}
#                          PUT    (/:locale)/sites/:id(.:format)      sites#update {:locale=>/en|ru/}
#                          DELETE (/:locale)/sites/:id(.:format)      sites#destroy {:locale=>/en|ru/}
#                          GET    /:locale(.:format)                  landing#index
#                     root GET    /                                   landing#index
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :sites, except: %i[new create]
    resources :logs, only: %i[index show destroy]

    root to: 'users#index'
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users

  scope '(:locale)', locale: /en|ru/ do
    resources :sites do
      get :ping_current, on: :member
      patch :ping_change, on: :member
      get :ping_new, on: :collection

      resources :logs, only: %i[index]
    end
  end

  get '/:locale' => 'landing#index'
  root to: 'landing#index'
end

app/models/site.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sites
#
#  id              :bigint           not null, primary key
#  checking_string :string
#  enabled         :boolean          default(TRUE)
#  interval        :integer          not null
#  last_pinged_at  :integer
#  name            :string           not null
#  protocol        :string           not null
#  status          :string           default("inactive")
#  timeout         :integer          default(10)
#  url             :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint
#
# Indexes
#
#  index_sites_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Site < ApplicationRecord
  include AASM

  SECONDS_IN_MINUTE = 60

  belongs_to :user
  has_many :logs, dependent: :destroy

  validates :name, presence: true
  validates :protocol, presence: true, inclusion: { in: %w[http:// https://] }

  validates :interval, presence: true, numericality: { only_integer: true }
  validates :timeout, numericality: { only_integer: true }

  validates :url, presence: true
  validate :validate_url_format

  # TODO: uncomment after config smtp-services for production
  # around_update :notify_about_changing_status

  aasm column: 'status' do
    state :inactive, initial: true
    state :down
    state :slow
    state :up
  end

  def full_url
    [protocol, url].join
  end

  def ping_time?
    minutes_from_last_ping >= interval && enabled?
  end

  private

  def minutes_from_last_ping
    (Time.now.utc.to_i - (last_pinged_at || created_at.to_i)) / SECONDS_IN_MINUTE
  end

  def validate_url_format
    return if url.blank? || full_url =~ URI::DEFAULT_PARSER.make_regexp

    errors.add :url, I18n.t('activerecord.errors.messages.url_format')
  end

  def notify_about_changing_status
    logger.info "Changes in status: #{changes}"
    is_status_changed = changes.key?('status')
    yield
    NotificationsMailer.status_changed(self).deliver_later if is_status_changed
  end
end

app/controllers/admin/sites_controller.rb
# frozen_string_literal: true

module Admin
  class SitesController < Admin::ApplicationController
    def valid_action?(name, resource = resource_class)
      %w[new].exclude?(name.to_s) && super
    end
  end
end

app/controllers/sites_controller.rb
# frozen_string_literal: true

class SitesController < ApplicationController
  LAST_LOGS_LIMIT = 5

  before_action :authenticate_user!
  before_action :load_site, only: %i[show edit update destroy ping_current ping_change]

  def index
    @query = current_user.sites.includes(:logs).ransack(params[:q])
    @sites = @query.result(distinct: true)
  end

  def new
    @site = current_user.sites.new
  end

  def show
    authorize @site

    logs = @site.logs
    @last_logs = logs.first(LAST_LOGS_LIMIT)

    query_params = params[:q] || default_query_params
    @query = logs.ransack(query_params)
    chart_logs = @query.result(distinct: true)

    options = params.key?(:filter) ? { filter: params[:filter] } : {}
    @data, @response_values = ChartService.call(chart_logs, options)
  end

  def create
    @site = current_user.sites.new(site_params)

    if @site.save
      redirect_to @site, notice: t('message.site_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @site
  end

  def update
    authorize @site

    if @site.update(site_params)
      redirect_to @site, notice: t('message.site_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @site

    @site.destroy

    redirect_to sites_path, notice: t('message.site_deleted')
  end

  def ping_current
    authorize @site

    render_ping_info_in_json(@site.full_url, ping_attrubutes)
  end

  def ping_new
    logger.info "Receiving url: #{params[:url]} timeout: #{params[:timeout]} checking: #{params[:checking_string]}"
    render_ping_info_in_json(params[:url], ping_params)
  end

  def ping_change
    authorize @site

    @site.update!(enabled: !@site.enabled)

    redirect_to @site
  end

  private

  def site_params
    params.require(:site).permit(:name, :url, :interval, :protocol, :timeout, :checking_string)
  end

  def ping_params
    params.permit(:timeout, :checking_string).compact_blank.as_json
  end

  def ping_attrubutes
    @site.attributes.slice('timeout', 'checking_string')
  end

  def load_site
    @site = Site.find(params[:id])
  end

  def render_ping_info_in_json(url, options)
    options['timeout'] = options['timeout'].to_i if options.key?('timeout')
    ping_info = PingService.call(url, options.symbolize_keys)
    render json: ping_info
  end

  def default_query_params
    { created_at_gteq: Time.current - 1.hour }
  end
end

app/views/sites/_chart.html.slim
.row.mb-1
  .col
    = area_chart @data, ytitle: t('sites.show.response_time'), empty: t('helpers.no_data'), loading: t('sites.show.loading'), download: { background: '#ffffff' }

app/views/sites/_chart_search_form.html.slim
.row.mb-3
  .col
    ul.nav.align-items-center
      li.nav-item
        = link_to t('form.last_hour'), { q: { created_at_gteq: Time.current - 1.hour } }, class: 'nav-link text-light bg-dark rounded-3 me-2'
      li.nav-item
        = link_to t('form.last_day'), { q: { created_at_gteq: Time.current - 1.day }, filter: 'hour' }, class: 'nav-link text-light bg-dark rounded-3'

      li.nav-item.ms-auto
        = search_form_for @query, url: @site, class: 'nav-item row align-items-center gx-2 gy-2' do |f|
          .col-auto
            = select_tag(:filter, options_for_select(['minute', 'hour']), class: 'form-select')
          .col-auto
            = f.datetime_local_field :created_at_gteq, class: 'form-control'
          .col-auto
            = f.datetime_local_field :created_at_lteq, class: 'form-control'

          .col-auto
            = f.submit class: 'btn btn-sm btn-dark'

app/views/sites/_form.html.slim
= form_with model: site, local: true do |f|
  ul.nav.nav-tabs.mb-3 role="tablist"
    li.nav-item
      button.nav-link.active data-bs-toggle="tab" data-bs-target="#required" type="button" role="tab" aria-controls="required" aria-selected="true" Required
    li.nav-item
      button.nav-link data-bs-toggle="tab" data-bs-target="#optional" type="button" role="tab" aria-controls="optional" aria-selected="false" Optional

  .tab-content
    #required.tab-pane.fade.show.active role="tabpanel" aria-labelledby="required-tab"
      .mb-3
        = f.label :name, t('activerecord.attributes.site.name'), class: 'form-label'
        = f.text_field :name, class: 'form-control'
        - site.errors.full_messages_for(:name).each do |message|
          .text-danger = message

      .mb-3
        = f.label :url, t('activerecord.attributes.site.url'), class: 'form-label'
        = f.text_field :url, class: 'form-control'
        - site.errors.full_messages_for(:url).each do |message|
          .text-danger = message

      .mb-3
        = f.label :interval, t('activerecord.attributes.site.interval'), class: "form-label"
        = f.number_field :interval, class: "form-control"
        small.form-text.text-muted = t('form.in_minutes')
        - site.errors.full_messages_for(:interval).each do |message|
          .text-danger = message

      .mb-3
        = f.label :protocol, t('activerecord.attributes.site.protocol'), class: "form-label"
        = f.select :protocol, [%w[http:// http://], %w[https:// https://]], {}, { class: "form-control" }

    #optional.tab-pane.fade role="tabpanel" aria-labelledby="optional-tab"
      .mb-3
        = f.label :timeout, t('activerecord.attributes.site.timeout'), class: 'form-label'
        = f.number_field :timeout, class: 'form-control'
        small.form-text.text-muted = t('form.in_seconds')
        - site.errors.full_messages_for(:timeout).each do |message|
          .text-danger = message

      .mb-3
        = f.label :checking_string, t('activerecord.attributes.site.checking_string'), class: 'form-label'
        = f.text_field :checking_string, class: 'form-control'

  = f.submit class: 'btn btn-dark w-100'

app/views/sites/_ping_form.html.slim
.d-flex.mt-3.ping-wrapper.align-items-center
  = link_to t('links.ping'), ping_new_sites_path, remote: true, data: { type: :json }, class: 'btn btn-outline-dark ping-link flex-shrink-0'
  .ms-3.ping-box.text-truncate

app/views/sites/_search_form.html.slim
.row.mb-3
  .col-12.mb-3
    = link_to t('form.filter'), '#filter_form', data: { 'bs-toggle': 'collapse' }, role: 'button', class: 'btn btn-sm btn-outline-dark', aria: { expanded: 'false', controls: 'filter_form' }
  .col.collapse#filter_form
    .row.align-items-center.gx-2
      .col-auto
        = link_to t('form.clear'), {}, class: 'btn btn-sm text-light bg-dark rounded-3'
      .col
        = search_form_for @query, class: 'row gx-2 align-items-center' do |f|
          .col-auto
            = f.label :status_eq, t('sites.index.status')
          .col-auto
            = f.select :status_eq, Site.aasm.states, { include_blank: t('form.all') }, class: 'form-select'

          .col-auto
            = f.label :protocol_eq, t('sites.index.protocol')
          .col-auto
            = f.select :protocol_eq, %w[http:// https://], { include_blank: t('form.all') }, class: 'form-select'

          .col-auto
            = f.label :logs_status_in, t('sites.index.last_pinged_result')
          .col-auto
            = f.select :logs_status_in, Log.aasm.states, { include_blank: t('form.all') }, class: 'form-select', multiple: true, size: "2"

          .col-auto
            = f.label :url_cont, t('sites.index.url')
          .col-auto
            = f.search_field :url_cont, class: 'form-control'

          .col-auto
            = f.submit class: 'btn btn-sm btn-dark'

app/views/sites/_site.html.slim
tr.position-relative
  td
    = status_name(site)
  td
    = link_to site.name, site, class: 'stretched-link text-decoration-none text-dark'
  td
    = site.protocol
  td
    = site.url
  td
    = site.interval

  td
    - if site.last_pinged_at
      = format_unix_time(site.last_pinged_at)
  td
    - if site.last_pinged_at
      = site.logs.first.status

app/views/sites/_site_body.html.slim
.row.mb-3
  .col-2
    .d-flex.justify-content-center.align-items-center.bg-light.rounded-3.h-100.border
      = format_status(@site)
  .col
    .border.p-3
      table.table.table-borderless
        thead
          tr
            th scope="col" = t('.url')
            th scope="col" = t('.min_response')
            th scope="col" = t('.max_response')
            th scope="col" = t('.average_response')
            th scope="col" = t('.created_at')
        tbody
          tr
            td = @site.full_url
            td
              = format_data(@response_values[:min])
            td
              = format_data(@response_values[:max])
            td
              = format_data(@response_values[:avg])
            td = format_unix_time(@site.created_at)
  .col-2
    nav.nav.flex-column.justify-content-around.h-100.px-3.settings
      = link_to ping_ability(@site), ping_change_site_path(@site), method: :patch, class: 'nav-item btn btn-secondary', data: { confirm: t('links.confirm') }
      = link_to t('links.settings'), edit_site_path(@site), class: 'nav-item btn btn-primary'
      = link_to t('links.delete'), @site, method: :delete, data: { confirm: t('links.confirm') }, class: 'nav-item btn btn-danger'

app/views/sites/edit.html.slim
- content_for :header do
  = t('.edit_site')

= render partial: 'form', locals: { site: @site }, layout: 'shared/site_form'

app/views/sites/index.html.slim
= render 'search_form'

.row
  .col
    table.table.table-hover.table-borderless
      thead
        tr
          th scope="col" = t('.status')
          th scope="col"
            = sort_link @query, :name, {}, class: 'text-dark'
          th scope="col" = t('.protocol')
          th scope="col" = t('.url')
          th scope="col" = t('.interval')
          th scope="col"
            = sort_link @query, :last_pinged_at, {}, class: 'text-dark'
          th scope="col" = t('.last_pinged_result')
      tbody.bg-light
        = render @sites

app/views/sites/new.html.slim
- content_for :header
  = t('.add_site')

= render partial: 'form', locals: { site: @site }, layout: 'shared/site_form'

app/views/sites/show.html.slim
section.site-info.mb-4
  .row.mb-3
    .col.text-center
      h4.h4 = @site.name

  = render 'site_body'

  .row.justify-content-center.ping-wrapper
    .col-7.d-flex.align-items-center
      = link_to t('links.ping'), ping_current_site_path(@site), remote: true, data: { type: :json }, class: 'btn btn-outline-dark ping-link flex-shrink-0'
      .ms-3.ping-box.text-truncate
    .col-1.d-flex.justify-content-end
      = link_to t('links.all_logs'), [@site, :logs], class: 'btn btn-outline-dark'

= render 'chart_search_form'

= render 'chart'

.row
  .col
    h5.h5.mt-3.text-center = t('.last_logs')
    table.table.table-hover
      thead
        tr
          th scope="col" = t('.time')
          th scope="col" = t('.status')
          th scope="col" = t('.response_time')
          th scope="col" = t('.response_message')
      tbody
        = render @last_logs